### ISSUE TITLE
EMAIL

### ISSUE THREAD

**Issue by HectorsGrav3** [Its-Vichy/0xGenerator#2]
Why dont you use temp mail?

**Comment by chiron852** [comment]
how do you make it work

**Comment by Its-Vichy** [comment]
temp-mail was detected by discord lmfao

**Comment by HectorsGrav3** [comment]
Is it? Because my token gen works with tempmail fine af

**Comment by Its-Vichy** [comment]
somes tempmail are detected

**Comment by HectorsGrav3** [comment]
fuck
