### ISSUE TITLE
Hostname mismatch

### ISSUE THREAD

**Issue by bonxz** [Its-Vichy/0xGenerator#3]
[DEBUG] Get fingerprint error: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'ptb.discordapp.com'. (_ssl.c:997)

**Comment by Its-Vichy** [comment]
Shit proxies use http

**Comment by chiron852** [comment]
how tf do you even use this-
